export const PATH = {
  root: '/',
  myPage: '/mypage',
  notification: '/notification',
  login: '/login',
  search: '/searchs',
  filter: '/filters',
  schedule: '/schedule',
  editSchedule: '/schedule/:id',
  signUp: '/signup',
  findPassword: 'find-password',
  detail: '/detail/',
  post: '/posts/:id',
  changePassword: '/change-password',
  commentModal: '/comment-modal',
  map: '/map/:id',
  setup: '/setup',
  notfound: '*',
};
